version: "{build}"

environment:
  global:
    nodejs_version: "LTS"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

build: off

test_script:
  - yarn test
